### PR TITLE
fix: manual `ToString` implementation for `RGB8`

### LINKED ISSUE #644: `RGB8` manually implements `ToString`
`ToString` is automatically implemented for any `struct` that implements the `Display` trait.

### PR DESCRIPTION
**Pull request by hamirmahal**
fixes #644.

### CODE REVIEW

File: src/asciicast/v2.rs [hunk 1]
```diff
@@ -319,9 +320,9 @@ impl serde::Serialize for RGB8 {
     }
 }
 
-impl ToString for RGB8 {
-    fn to_string(&self) -> String {
-        format!("#{:0>2x}{:0>2x}{:0>2x}", self.0.r, self.0.g, self.0.b)
+impl fmt::Display for RGB8 {
+    fn fmt(&self, f: &mut std::fmt::Formatter) -> fmt::Result {
+        write!(f, "#{:0>2x}{:0>2x}{:0>2x}", self.0.r, self.0.g, self.0.b)
```
Comment (hamirmahal) [inline src/asciicast/v2.rs:325]: This is a bit more idiomatic.

**Comment by ku1ik** [comment]
Yup, missed that. Definitely better 👍 Thanks!

**Comment by hamirmahal** [comment]
You're welcome!
